<div class="container">    
      <div class="row">
        <div class="card-login">
          <div class="card">
            <div class="card-header">
              <h4>Entrar no Sistema</h4>
            </div>
            <div id="corpo-form" class="card-body">
              <form method="POST" action="/autenticar">
                <div class="form-group">
                  <input name="matricula" type="text" class="form-control" placeholder="Matricula" maxlength="8">
                </div>
                <div class="form-group">
                  <input name="senha" type="password" class="form-control" placeholder="Senha" maxlength="32">
                </div>
                <button class="btn btn-lg btn-info btn-block" type="submit" value="ACESSAR">Entrar</button>
              </form>
              <?php if($this->view->login =='erro'){ ?>
                <span class="form-text text-danger">Erro login invalido</span>
              <?php }?>
            </div>
          </div>
        </div>
    </div>
    