<div class="container">
    <h2>Encaminhar Chamado</h2>
    <form>
        <div class="form-group">
            <label for="nivel">Nivel</label>
            <select class="form-control" id="nivel">
                <option>1</option>
                <option>2</option>
                <option>Diretor</option>
            </select>
        </div>
        <div class="form-group">
            <label for="setordesejado">Setor Desejado</label>
            <select class="form-control" id="exampleFormControlSelect1">
                <option>naosei</option>
                <option>naosei</option>
                <option>naosei</option>
            </select>
        </div>
        <div class="form-group">
            <label for="servico">Serviço</label>
            <select class="form-control" id="exampleFormControlSelect1">
                <option>naosei</option>
                <option>naosei</option>
                <option>naosei</option>
            </select>
        </div>
        <div class="form-group">
            <label for="motivo">Motivo:</label>
            <textarea class="form-control" id="motivo" rows="3"></textarea>
        </div>
            <button type="submit" class="btn btn-primary pull-right">Encaminhar</button>
        <ul>
            <li class="btn-group pull-right"><a class="btn btn-warning" href="/home.html">Cancelar</a></li>
        </ul>
    </form>
</div>
