<div class="container">
    <p>
        <div class="btn-group"><a class="btn btn-primary" href="/nav/criar_usuario">Criar Novo Usuário</a></div>
    <!-- ----------------Opções de gerencia de usuarios ------------------------------------------------------------------------------ -->
    </p> 
    <div class="table-resnposive">
        <table class="table table-bordered table-hover">
        <thead>
            <tr>
            <th>Nome</th>
            <th>Matricula</th>
            <th>Email</th>
            <th>Telefone</th>            
            <th>Nivel</th>
            </tr>
        </thead>
        <tbody >
            <?php //armaznr todos os dados do metodo em uma variavel
                $dados = $this->view->lista; 
                if($dados > 0){
                    for($i = 0; $i < count($dados); $i++){
                        echo"<tr>";
                        foreach($dados[$i] as $key => $value){
                            if($key!="id_usuario" ){
                                if($value !="concluido"){
                                    echo "<td>".$value."</td>";
                                }  
                            }
                        }?>
                        <td>
                          <a class="btn b" href="/excluirUsuario?id=<?php echo $dados[$i]['id_usuario'];?>"><img src="../icons/icon_cancel.png" alt="Botão Cancelar" title="Botão Cancelar"></a>
                          <a class="btn b" href=""><img src="../icons/icon.png" alt="Botão Atualizar" title="Botão Atualizar"></a>
                        </td>
                        <?php
                        echo"</tr>";
                    }
                }
                ?>
            </tr>
        </tbody>
        </table>
    </div>
</div>